config/routes.rb
Fireworks::Application.routes.draw do

  devise_for :ads_users, controllers: { sessions: "ads_users/sessions"}

	resources :ads_users, :ads_user_id => /[^\/]+/ , only: [ :show ]  do
	end

  resources :licservers, :only => [:index, :show, :create, :update ]  do
    get 'summary'
    resources :features, :only => [:index, :show, :update] do
      get 'get_data'
      get 'histogram_data'
      get 'usage_report_data'
      get 'users'
      delete 'users', :to => 'features#kill_users'
      delete 'user', :to => 'features#kill_user'
    end
  end

  resources :tags, :only => [:index] do
  end

  resources :users, :only => [:index, :show] do
  end

  get 'disclaimer' => 'welcome#disclaimer'
  get 'search' => 'welcome#search'

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def download_client
    if params.has_key? :type then
      if params[:type] == 'Windows' then
        send_file "#{Rails.root}/lib/client/fireworks_client_windows.zip"
      elsif params[:type] == 'Mac Os X' then
        send_file "#{Rails.root}/lib/client/fireworks_client_mac.zip"
      end
    end
  end

  def about
  end

  def tech
  end

  def notice
    render :partial => 'notice', :locals => { :msg => params[:msg] }
  end

	def disclaimer
	end

  #must have query
  def search
    if params.has_key? :query then
      @tags = Tag.search(params[:query])
    else
      @tags = Tag.select(:title).uniq.map{ |x|
        { :title => x.title, :licservers => Tag.where(:title => x.title).map{ |y| y.licserver } }
      }
    end

    respond_to do |format|
      format.template {
        render :file => "tags/index.template", :locals => { :'@tags' => @tags }
      }
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_footer.html.erb
<div id="footer_box">
  <div id="footer_inner_box">
    <div title="frontpage" id="footer_line"><%= link_to "f",welcome_index_path %></div>
    <div title="about" id="footer_line"><%= link_to "a",welcome_about_path %></div>
    <div title="tags" id="footer_line"><%= link_to "#",tags_path %></div>
    <div title="License Server" id="footer_line"><%= link_to "@",licservers_path %></div>
  </div>
</div>

app/views/welcome/_notice.html.haml
.alert.alert-success
  %button.close{ :type => 'button', :data => { :dismiss => 'alert' } } &times;
  = msg

app/views/welcome/disclaimer.html.haml
.container
	%h2 Disclaimer
	%p The Software is released under the apache license with the following Terms and Conditions:-
	%pre
		= render :file => 'public/license.txt'

app/views/welcome/index.html.haml
- if !ads_user_signed_in? then
  .jumbotron.jumbotron-fluid{ :style => "background:url(9482.jpg); height:100vh; background-size: cover; color:white;"}
    .container
      %h1.display-3 Fireworks
      %p.lead Flexera and Reprise License Monitoring
.jumbotron.jumbotron-fluid
  .container-fluid
    %fieldset.form-group
      %input.form-control#search-query{ :type => "text", :placeholder => "Search ... "}
    #tags-target{ :'data-source' => tags_path(:format => :template) }
      %i.fa.fa-cog.fa-spin.fa-2x

app/views/welcome/search.html.haml
.container-fluid
  .row{ :style => "padding-top:70px;"}
    .col-xs-12
      %fieldset.form-group
        %input.form-control{ :type => "text", :placeholder => "Search ... "}
  .row
    .col-xs-12
      %p Search Results here