config/routes.rb
Fireworks::Application.routes.draw do

  devise_for :ads_users, controllers: { sessions: "ads_users/sessions"}

	resources :ads_users, :ads_user_id => /[^\/]+/ , only: [ :show ]  do
	end

  resources :licservers, :only => [:index, :show, :create, :update ]  do
    get 'summary'
    resources :features, :only => [:index, :show, :update] do
      get 'get_data'
      get 'histogram_data'
      get 'usage_report_data'
      get 'users'
      delete 'users', :to => 'features#kill_users'
      delete 'user', :to => 'features#kill_user'
    end
  end

  resources :tags, :only => [:index] do
  end

  resources :users, :only => [:index, :show] do
  end

  get 'disclaimer' => 'welcome#disclaimer'
  get 'search' => 'welcome#search'

  root :to => 'welcome#index'

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :licserver
  belongs_to :feature_header
  #attr_accessible :current, :max, :name, :licserver_id
  has_many :machine_features
  has_many :machines, :through => :machine_features

  #update features
  def self.update_features(licserver_id)
		# suppress sql output for a while
		ActiveRecord::Base.logger = nil

    #update features here
    licserver = Licserver.find(licserver_id)
    @fullname = licserver.port.to_s + '@' + licserver.server

		Rails.logger.info "getting stats for #{@fullname} "
    #new way to generate features,users and machine  data
    output = `#{Rails.root}/lib/myplugin/lmutil lmstat -a -c #{@fullname} | grep -vi "error"`
    header = /Users.*/

    #split the output into headers of "Users of <feature name>...."
    #sections = output.scan(/(?m)#{header}.*?(?=#{header})|\Z/)
    sections = output.force_encoding("ISO-8859-1").encode("utf-8", replace: nil).scan(/(?m)#{header}.*?(?=#{header})/)
    if sections.count == 0 then
      #handle if there's only 1 feature
      sections = output.force_encoding("ISO-8859-1").encode("utf-8", replace: nil).scan(/(?m)#{header}.*/)
    end
    sections.each do |section|
      feature_line = section.lines.grep(/Users/).first
      unless feature_line.nil?
        #create new headers where necessary
        feature_name = feature_line.split(" ")[2].gsub(/:/, '')
        #Rails.logger.debug "Getting feature stats for #{feature_name}"
        if ( licserver.feature_headers.where(:name => feature_name ).empty? ) then
          licserver.feature_headers.create( :name => feature_name, :last_seen => DateTime.now ).save!
        end

        feature = licserver.feature_headers.where(:name => feature_name).first.features.create(
          :name => feature_name, :current => feature_line.split[10], :max => feature_line.split[5],
          :licserver_id => licserver.id
        )
        licserver.feature_headers.where(:name => feature_name).first.update_attribute(:last_seen, DateTime.now)
        feature.save!
      end

			#collect user info
      user_lines = section.lines.grep(/start/)
      unless user_lines.nil? || user_lines.empty?
        user_lines.each do |user_line|
					user_line_array = user_line.scan(/\S+/)
					version_index = user_line_array.index{ |x| x =~ /\(\S+\)/ }

					#the version keyword is not in the string, so use the (server/port) keywork instead
					if version_index.nil? then
						version_index = user_line_array.index{ |x| x =~ /\(\S+/ }
					end

          User.generate_features_data(
						user_line_array[0..zero_if_negative(version_index-3)].join(" "), user_line_array[version_index-2] , feature.id
					)
        end
      end
    end

  end

  #get list of current users
  def self.current_users(licserver_id,features_id)
    licserver = Licserver.find(licserver_id)
    @fullname = licserver.port.to_s + '@' + licserver.server

    output = `#{Rails.root}/lib/myplugin/lmutil lmstat -a -c #{@fullname} -f #{features_id} | gawk '/start/ { print $0 }'`

    users = []
    output.each_line do |line|
			correction = 0
			line_array = line.scan(/\S+/)
			version_index = line_array.index{ |x| x =~ /\(\S+\)/ }
			if version_index.nil? then
				version_index = line_array.index{ |x| x =~ /\(\S+/ }
				correction = -1
			end
			#need to handle cases where the version keyword is not there
      users << { :user => line_array[0..zero_if_negative(version_index-3)].join(" "),
				:user_id => User.find_by_name( line_array[0..version_index-3].join(" ") ),
				:machine => line_array[version_index-2],
        :host_id => line_array[version_index+correction+1].split('/')[0].gsub(/\(/, ''),
        :port_id => line_array[version_index+correction+1].split('/')[1],
				:handle => line_array[version_index+correction+2].gsub(/\)/, '').gsub(/,/, ''),
        :since => Time.parse(line_array[version_index+correction+4..version_index+correction+6].reverse.join(" ")).to_datetime ,
        :lic_count => line_array[version_index+correction+7]
			}
    end

    return users
  end

  #kill users at will
  def self.kill_user(licserver_fullname, feature_id, host_id, port_id, handle)
    output = `#{Rails.root}/lib/myplugin/lmutil lmremove -c #{licserver_fullname} -h #{feature_id} #{host_id} #{port_id} #{handle}`

    return output
  end

  #maintaince function:-
  # - remove features that somehow got updated here through update_features function
  def self.remove_old_f(licserver_id)
    licserver = Licserver.find(licserver_id)
    @lostFeatures = licserver.features.select("name, count(name) as l_count").group("name").having("count(name) = 1")

    #start killing them
    transaction do
      @lostFeatures.each do |lostF|
        @lostFList = licserver.features.where("name = ?", lostF.name)
        @lostFList.each do |lostFListDetail|
          @fToDestory = licserver.features.find(lostFListDetail.id)
          @fToDestory.destroy
        end
      end
    end
  end

  #maintainces function
  #build feature_headers line from features that don't have feature_header_id
  def self.build_feature_headers
    #rebuild 1000 at a time
    while Feature.where(:feature_header_id => nil).count != 0
      transaction do
        Feature.where(:feature_header_id => nil).order('id desc').limit(5000).each do |f|
          #find the feature header, otherwise, built a new one
          fh = Licserver.find(f.licserver_id).feature_headers.where(:name => f.name).first
          if fh.nil? then
            fh = Licserver.find(f.licserver_id).feature_headers.new( :name => f.name)
            fh.save!
          end

          f.update_attribute(:feature_header_id, fh.id)
        end
      end
    end
  end

  #find and kill idle users
  #return list of users that died
  def self.check_idle_users(licserver_id)
    licserver = Licserver.find(licserver_id)
    @fullname = licserver.port.to_s + '@' + licserver.server

    puts "Kill Idle users for " + @fullname
    #get list of current users and return a kill list
    lm_output =`#{Rails.root}/lib/myplugin/lmutil lmstat -a -c #{@fullname} | gawk '/Users/ { print $0 } /start/ { print $1, $2, $5, $6, $8, $9, $10 }'`

    output = Array.new
    feature = String.new
    lm_output.each_line do | line |
      if line.include? 'Users of' then
        feature = line.split[2].gsub(':', '')
        #next
      else
        lineSplit = line.split
        user = lineSplit[0]
        client_host = lineSplit[1]
        start_time = DateTime.parse(lineSplit[4..6].join(' ').sub(',','')+DateTime.now.zone)
        @idleUser =  IdleUser.where('user = ? and hostname =?', user, client_host).first

        #check idle parameters
        if (@idleUser.nil?  && start_time < 2.hours.ago) ||
          (!@idleUser.nil? && @idleUser.idle.to_i / 1000 > 60*30) ||
          ( !@idleUser.nil? && @idleUser.updated_at < 2.hours.ago) then
            #user not registered and has been using for more than 2 hours
            #user is registered and has been idle for more that 30 minutes
            #user is registered and has not check in more than 2 hours
            server_host = lineSplit[2].split('/')[0].sub('(', '')
            port_host = lineSplit[2].split('/')[1].to_i
            server_handle = lineSplit[3].to_i

            temp = { :feature => feature, :user => user, :client_host => client_host, :server_host => server_host,
              :port_host => port_host, :server_handle => server_handle , :start_time => start_time}

            output.push temp
        end #@idleUser.nil?
      end #line.includes?
    end #each_line

    #kill them
    output.each do | thisUser |
      Feature.kill_user @fullname, thisUser[:feature], thisUser[:server_host],
        thisUser[:port_host], thisUser[:server_handle]
    end

    return output
  end

  #generate last 30 days stats
  def self.generate_monthly_stats(licserver_id, feature_id, office_hours)

    #generate default stats
      #features_list = Licserver.find(licserver_id).features.find(:all,
      #  :conditions => { :name => feature_id, :created_at => 30.days.ago..DateTime.now })
      features_list = Licserver.find(licserver_id).features.where( :name => feature_id, :created_at => 30.days.ago..DateTime.now )

    if office_hours == true then
      #filter to office hours only
      #office hours is from 8am to 5pm
      features_list = features_list.select { |thisf| thisf.created_at.localtime.hour > 8 &&
        thisf.created_at.localtime.hour < 17 && thisf.created_at.localtime.wday != 0 &&
        thisf.created_at.localtime.wday != 6 }
    end

    #do the countings
    features_sorted = features_list.group_by{ |item| item.current }.reject{ |k,v| k.nil? || k[0].nil? }
    sum = 0
    features = features_sorted.inject(Hash.new(0)) { |h,e| h[e[0]] = e[1].count; h }.to_a.sort.map {
      |x| [ x[0], sum += x[1] ]
    }

    return features
  end

  # generate csv from features of licserver_id bearing the feature_name
  def self.to_csv(licserver_id, feature_name)
    csv_string = String.new

  end

	# kill users which holding more than one license
	def self.kill_dup_users(licserver_id, feature_name)
		#get licserver full name
		licserver = Licserver.find(licserver_id)
		licserver_name = [licserver.port, licserver.server].join('@')

		#get list of current users
		current_users = self.current_users(licserver_id, feature_name)
		current_users = current_users - current_users.select{ |x| x[:user_id].nil? }
		current_users = current_users - current_users.select{ |x| x[:user_id].uniq_exempt == true }

		#get dup users
		dup_list = current_users.select{ |e| current_users.count{ |x| x[:user] == e[:user] } > 1 }

		#kill the latest sessions
		dup_list.each.with_index do |e,i|
			if i != 0 && e[:user] == dup_list[i-1][:user] then
				Rails.logger.info "#{ DateTime.now.strftime } : Killing #{ e[:user] }@#{e[:machine]}, #{ e[:since] } for holding multiple #{feature_name} seats"
				#self.kill_user(licserver_id, feature_name, e[:host_id], e[:port_id], e[:handle])

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
	before_filter :authenticate_ads_user!, :only => [ :kill ]

  # GET    /licservers/:licserver_id/features/:id(.:format)
  def show
    respond_to do |format|
			format.html {
				@licserver = Licserver.find(params[:licserver_id])
			}
			format.json {
				feature = FeatureHeader.where(:licserver_id => params[:licserver_id], :name => params[:id]).first
				render :json => feature
			}
			format.template
    end
  end

	#update settings for the feature
	# PATCH  /licservers/:licserver_id/features/:id
	def update
		#find the feature header
		feature = FeatureHeader.where(:licserver_id => params[:licserver_id], :name => params[:id]).first

		if feature.nil? then
			render :nothign => true, :status => :not_found
			return
		else
			#update the feature
			if params.has_key? :'enforce-uniq' then
				feature.update_attribute(:uniq_users, true)
			else
				feature.update_attribute(:uniq_users, false)
			end
			render :nothing => true, :status => :ok
		end
	end

	# DELETE /licservers/:licserver_id/features/:feature_id/user(.:format)
  def kill_user
    #kill user here
		licserver = Licserver.find(params[:licserver_id])
    @output = licserver.kill_user(
			{ :feature => params[:feature_id], :host => params[:host_id], :port => params[:port_id], :handle => params[:handle]}
		)

    respond_to do |format|
			format.js
    end
  end

	#nuke users
	# DELETE /licservers/:licserver_id/features/:feature_id/users(.:format)
	def kill_users
		licserver = Licserver.find(params[:licserver_id])
		#get users list
		users = licserver.current_users( params[:feature_id])

		#mass kill them
		users.each do |user|
			licserver.kill_user({ :feature => params[:feature_id],
				:host => user[:host_id], :port => user[:port_id], :handle => user[:handle]})
		end

		respond_to do |format|
				format.js {
					render :nothing => true, :status => :ok
				}
		end
	end

	def users
		@users = Licserver.find(params[:licserver_id]).current_users(params[:feature_id])
	end

  # GET    /licservers/:licserver_id/features/:feature_id/get_data(.:format)
  # generate data for features params[:feature_id] from licserver params[:licserver_id]
  # will return 10000 data points at at time beginning from start_id or Feature.last.id and the previous
  # 100 points in the format of
  #
  #   [ { name:current, data:[ [created_at*1000, x1], ...[created_at*1000, xN] ] },
  #     { name:max, data[ [created_at*1000, x1], ...[created_at*1000, xN] ] } ]
  #
  # options:
  # start_id      take data point with this start id and the previous 10000 data points
  def get_data
    @licserver = Licserver.find(params[:licserver_id])
    feature_name = params[:feature_id]
    if params.has_key? :start_id then
      start_id = params[:start_id].to_i - 1
    else
      start_id = Feature.last.id
    end
		start_date = Feature.find(start_id).created_at
		data_points = params.has_key?(:start_id) ? 1000 : 200

		# we partition the features table by date, so include date so oracle will know which partition to go
    @features = @licserver.features.where{(features.created_at.lt start_date) & (features.id.lteq start_id) & (features.name.eq feature_name) }.
      limit(data_points).order('features.id desc')

    output = [ { :name => 'current' , :data => [] }, { :name => 'max', :data => [] } ]
    @features.each do |x|
      output[0][:data] << [x.created_at.to_i*1000, x.current, x.id]
      output[1][:data] << [x.created_at.to_i*1000, x.max]
    end

    respond_to do |format|
      format.json { render :json => { :last_id => @features.empty? ? 0 : @features.min.id, :data => output  } }
    end
  end

	# GET    /licservers/:licserver_id/features/:feature_id/histogram_data
	def histogram_data
		licserver = Licserver.find(params[:licserver_id])

		office_hours = licserver.usage_histogram_data(params[:feature_id])
		all_hours = licserver.usage_histogram_data(params[:feature_id], false)

		respond_to do |format|
			format.json { render :json => { :office => office_hours, :all => all_hours }  }
		end
	end

	# licserver_feature_usage_report_data
	#  GET    /licservers/:licserver_id/features/:feature_id/usage_report_data(.:format)
	def usage_report_data
		data = Licserver.find(params[:licserver_id]).usage_report_data( params[:feature_id] )

		respond_to do |format|
			format.json { render :json => data }
		end
	end

	def feature_header_params
		params.require(:feature_header).permit( :name, :licserver_id, :feature_id, :last_seen )
	end

	def feature_params
		params.require(:feature).permit( :current, :max, :name, :licserver_id )
	end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/kill_user.js.haml
$("#{ params[:target]}").fadeOut();

app/views/features/show.html.haml
- content_for :head do
  = " #{params[:id]} in #{@licserver.get_port_at_server} -"
.container{:style => "margin-top:70px;"}
  .row
    .col-xs-12
      %ol.breadcrumb
        %li
          %a{ :href => licserver_path(@licserver) } #{ @licserver.get_port_at_server }
        %li.active #{ params[:id]}
    .col-xs-12
      = render :file => "features/show.template.haml"
:javascript
  console.log('setup collapse on individual page');
  $(document).find('.collapse').each( function(){
    if($(this).attr('data-load-target') == null){
      setup_collapse($(this));
    } else {
      setup_collapse($(this), $(this).attr('data-load-target'));
    };
  });

app/views/features/show.template.haml
- random_id = SecureRandom.hex(8)
.list-group{ :id => random_id }
  %li.list-group-item
    %a.btn.btn-secondary{ :href => licserver_feature_path( params[:licserver_id], params[:id] ), :target => "_blank"}
      %i.fa.fa-external-link
    - if ads_user_signed_in? then
      %button.btn.btn-secondary{ :type => "button", :id => "settings-#{random_id}" ,
        :data => { :toggle => "modal", :target => '#feature-settings-modal', :random => random_id,
          :feature => params[:id ], :'info-path' => licserver_feature_path(params[:licserver_id], params[:id]) } }
        %i.fa.fa-cog
  %a.list-group-item{ :href => "#graph-collapse-#{random_id} ", :'data-toggle' => 'collapse'}
    %h6 Daily graph
  .collapse.in{ :id => "graph-collapse-#{random_id}"}
    .list-group-item
      %div{ :id => "graph-#{random_id}",
        :data => { :'graph-source' => licserver_feature_get_data_path(params[:licserver_id], params[:id], :format => :json ), :'start-id' => -1 } }
      %div
        %button.btn.btn-secondary{ :type => 'button', :'data-target' => "#graph-#{random_id}", :id => "graph-load-#{random_id}" }
          %i.fa.fa-backward
  %a.list-group-item{ :href => "#user-collapse-#{random_id}", :'data-toggle' => 'collapse'}
    %h6 Current Users
  .collapse{ :id => "user-collapse-#{random_id}",
    :data => { :source => licserver_feature_users_path( params[:licserver_id], params[:id], :format => :template), :plsload => 'yes',
      :'load-target' => "#user-list-#{random_id}"} }
    .list-group-item
      %button.btn.btn-primary{ :type => "button", :id => "user-refresh-#{random_id}"}
        %i.fa.fa-refresh
      - if ads_user_signed_in? then
        %button.btn.btn-danger{:id => "nuke-em-#{random_id}", :type => "button",
          :data => { :toggle => 'modal', :target => '#nuke-em-modal', :random => random_id, :feature => params[:id], :'kill-path' => licserver_feature_users_path( params[:licserver_id], params[:id])} }
          %i.fa.fa-bomb
        %button.btn.btn-info{ :type => "button", :data => { :toggle => 'modal', :target => '#mail-modal'}}
          %i.fa.fa-envelope
    .list-group-item{ :id => "user-list-#{random_id}"}
      %i.fa.fa-cog.fa-spin
  %a.list-group-item{ :href => "#other-collapse-#{random_id}", :'data-toggle' => 'collapse' }
    %h6 Other Items
  .collapse{ :id => "other-collapse-#{random_id}"}
    .list-group-item
      %p 30 Days Usage Histogram
      %div{:id => "histogram-#{random_id}", :data => { :loaded => 'no',  :'graph-source' => licserver_feature_histogram_data_path(params[:licserver_id], params[:id], :format => :json ) } }
    .list-group-item
      %p Usage by Company / Group
      %button.btn.btn-secondary{ :type => 'button', :id => "generate-usage-rpt-#{random_id}"}
        %i.fa.fa-bar-chart
        Click to Load
      %div{ :id => "usage-by-company-graph-#{random_id}", :data => { :'graph-source' => licserver_feature_usage_report_data_path(params[:licserver_id], params[:id], :format => :json ) } }
:javascript
  Highcharts.setOptions({ global: { useUTC: false } });

  load_graph( $('#graph-#{ random_id}'), { title: { text:'#{params[:id]}'} } );

  //setup the graph loading button
  $('#graph-load-#{random_id}').on('click', function(){
    var this_button = $(this);
    var graph_handle = $('#graph-#{random_id}');

    //disable the button
    this_button.attr('disabled', 'disabled');

    //load and dump data
    $.get( graph_handle.attr('data-graph-source'), { start_id: graph_handle.attr('data-start-id')}, function(data){
      var chart_handle = graph_handle.highcharts();
      for(i=0; i< data['data'][0]['data'].length; i++){
        chart_handle.series[0].addPoint( data['data'][0]['data'][i], false, false);
        chart_handle.series[1].addPoint( data['data'][1]['data'][i], false, false);
      };
      graph_handle.attr('data-start-id', data['last_id']);
      chart_handle.redraw();
    });

    //enable the button
    this_button.removeAttr('disabled');
  })

  //refresh user
  $('#user-refresh-#{random_id}').on('click', function(){
    //reload the user list
    $('#user-list-#{random_id}').empty().append(
      $.parseHTML('<i class="fa fa-cog fa-spin"></i>')
    );
    $.get($('#user-collapse-#{random_id}').attr('data-source'), null, function(data){
        $("#user-list-#{random_id}").empty().append(data).ready(function(){
          $('#user-list-#{random_id}').find('.collapse').each( function() {
              setup_collapse( $(this));
          });
        });
    });
  });

  //load histogram data
  $('#other-collapse-#{random_id}').on('show.collapse.bs', function(){

    if( $('#histogram-#{random_id}').attr('data-loaded') == 'no') {
      console.log('start loading other data here');
      usage_histogram_graph( $('#histogram-#{random_id}'), {
        title: { text: '#{ params[:id]} 30-days Usage Historgram'}
      });

      $('#histogram-#{random_id}').attr('data-loaded', 'yes');
    }
  });

  //feature usage
  $('#generate-usage-rpt-#{random_id}').click( function(){
    $(this).remove();
    $('#usage-by-company-graph-#{random_id}').append(
      $.parseHTML('<i class="fa fa-cog fa-spin"></i>')
    )

    company_usage_graph( $('#usage-by-company-graph-#{random_id}'), {
      title: { text: '#{ params[:id]} 30-days usage by Company & Department'}
    });
  });

app/views/features/users.template.haml
%table.table
  - if @users.nil? then
    %tr
      %td{:colspan => 2} No Users Detected
  - else
    %tr
      %td{:colspan => 2} Last Updated: #{ DateTime.now } (#{@users.count} User(s))
    - @users.each do |user|
      - random_id = SecureRandom.hex(8)
      %tr{ :id => "user-#{random_id}"}
        %td
          #{link_to user[:user], "#user-info-#{random_id}", :'data-toggle' => 'collapse'}@#{user[:machine]} since #{user[:since]}
          .collapse{ :style => "margin-top:15px;", :id => "user-info-#{random_id}", :data => { :plsload => "yes", :source => user_path(user[:user_id].id, :format => :template) }}
            %i.fa.fa-cog.fa-spin
        - if ads_user_signed_in? then
          %td
            = button_to( "&times;".html_safe,
              licserver_feature_user_path( params[:licserver_id], params[:feature_id], :handle => user[:handle], :target => "#user-#{random_id}", :host_id => user[:host_id], :port_id => user[:port_id], :user => user[:user]),
              { :method => :delete, :class => 'btn btn-danger btn-sm', :remote => true } )